<a href="https://colab.research.google.com/github/DEEPESH98/Machine-Larning/blob/master/Imputer_Onhot_LabelEncod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
# reading csv file from URL
df=pd.read_csv('info.csv')

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [104]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [0]:
#iloc=index location   /  taki header hat jaye
x=df.iloc[:,0:].values

In [106]:
x


array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# removing missing values or replacing missing value with some relevent data
#df.describe()
from sklearn.preprocessing import  Imputer


In [108]:
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [109]:
imp

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [0]:
impute=imp.fit(x[:,1:3]) # this is only fiting of colums that we want to process/isese upper vale process ko keha kam ker na he

In [111]:
impute

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [0]:
# time for transforming the fitted colums
x[:,1:3]=impute.transform(x[:,1:3])


In [113]:
x # pure edge ki mean value he ye jo file huii he

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# string label int / float
from sklearn.preprocessing import LabelEncoder

In [0]:
cont=LabelEncoder() # this is for country labeling

In [116]:
cont

LabelEncoder()

In [0]:
# now apply colum first in this labelEn
x[:,0]=cont.fit_transform(x[:,0])

In [118]:
x

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# label last colum 
p=LabelEncoder()

In [0]:
x[:,3]=p.fit_transform(x[:,3])

In [121]:
x

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [0]:
# now encoding first column --- making sub-colum of first column

from sklearn.preprocessing import OneHotEncoder

In [123]:
OneHotEncoder()

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [0]:
firstcl=OneHotEncoder(categorical_features=[0]) # defining exact colum number where we want to make category


In [125]:
x=firstcl.fit_transform(x).toarray() # after trnsformation we need to convert into numpy array

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [126]:
x

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04, 

In [127]:
x.astype(int)  # to show in int only  / notebook me diya hii ki ye esa kuuu he 

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 63777,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    38, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])