<a href="https://colab.research.google.com/github/DEEPESH98/Machine-Larning/blob/master/Tensorflow_prec2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
# Create Tensorflow object called tensor
hello_constant = tf.constant('Hello World!')

In [3]:
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

In [0]:
#Tensorflow Session()  is a running part

In [6]:
with tf.Session() as sess:
  # run the tf.contaant operation in the session
  output = sess.run(hello_constant) # decode()
  print(output)

b'Hello World!'


In [7]:
'''three type of data 
1. constant
2. Placeholder
3. variable
'''

'three type of data \n1. constant\n2. Placeholder\n3. variable\n'

In [8]:
# Check version of the tensorflow
print(tf.__version__)

1.14.0


In [11]:
# initiate tensorflow constant
node1=tf.constant(3.0,tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
print(node1,node2)

Tensor("Const_5:0", shape=(), dtype=float32) Tensor("Const_6:0", shape=(), dtype=float32)


In [12]:
sess =tf.Session()
print(sess.run([node1,node2]))
sess.close()

[3.0, 4.0]


In [0]:
# Example: multiple two constant

In [16]:
a = tf.constant(4.0)
b = tf.constant(6.0)
c=a*b
c

<tf.Tensor 'mul_1:0' shape=() dtype=float32>

In [22]:
# evaluate the tensor
sess = tf.Session()
print(sess.run(c))
sess.close()


24.0


In [0]:
# Tensorflow placeholder

In [0]:
import tensorflow as tf

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

adder_node=a+b
sess=tf.Session()
#print(sess.run(adder_node,feed_dict={a:[1,2,3], b:[2,3,4]}))

In [33]:
print(sess.run(adder_node,feed_dict={a:[1,2,3], b:[2,3,4]}))

[3. 5. 7.]


In [35]:
# Do another calculation
Mult_5 = adder_node*5
#print(sess.run(Mult_5,{a:[[1,2,3],[2,3,4],[3,2,1]],b: [[2,3,4],[4,3,2],[1,2,3]]}))

[[15. 25. 35.]
 [30. 30. 30.]
 [20. 20. 20.]]


In [0]:
# Tensorflow variable
# Variable allow us to add trainable prameters to graph
# y = .2 + .3*x

In [0]:
import tensorflow as tf

In [48]:
w1 = tf.Variable([.5], tf.float32)
# important: need to run below code to initialize the variable()
init = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(w1))
sess.close()

[0.5]


In [0]:
# y = b+ w*x
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.9], tf.float32)
x = tf.placeholder(tf.float32)

linear_model = w*x +b
init = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
#print(sess.run(linear_model,{x:[1,2,3,4,5,6,7]}))
#sess.close()


In [56]:
print(sess.run(linear_model,{x:[1,2,3,4,5,6,7]}))
sess.close()

[-5.9999996e-01 -2.9999995e-01  5.9604645e-08  3.0000007e-01
  6.0000002e-01  9.0000010e-01  1.2000002e+00]


In [0]:
#Tensorflow Math

In [0]:
x = tf.add(5,2)

In [59]:
x

<tf.Tensor 'Add_9:0' shape=() dtype=int32>

In [0]:
y=tf.subtract(10,4)

In [0]:
z=tf.multiply(2,5)

In [0]:
#Converting data type

In [66]:
with tf.Session() as sess:
  print(sess.run(tf.subtract(tf.cast(tf.constant(2.0),tf.int32),tf.constant(1)))) 

1
